import fs from 'fs';
import path from 'path';

const cloudinaryUrlsPath = path.join(process.cwd(), 'cloudinary_urls.txt');
const cloudinaryUrls = fs.readFileSync(cloudinaryUrlsPath, 'utf-8').split('\n').filter(Boolean);

const imageMap = new Map<string, string>();
cloudinaryUrls.forEach(url => {
  const parts = url.split('/');
  const filename = parts[parts.length - 1].trim();
  if (filename) {
    imageMap.set(filename, url.trim());
  }
});

function getCloudinaryUrls(filenames: string[]): string[] {
  return filenames
    .map(filename => imageMap.get(filename))
    .filter(Boolean) as string[];
}

function getRandomImage(): string[] {
  const randomIndex = Math.floor(Math.random() * cloudinaryUrls.length);
  return [cloudinaryUrls[randomIndex]];
}

export const categoryData = [
  { name: 'Engine Parts', slug: 'engine-parts', description: 'Engine components, timing belts, fuel pumps, and more', display_order: 1 },
  { name: 'Body Parts', slug: 'body-parts', description: 'Bumpers, doors, fenders, and exterior components', display_order: 2 },
  { name: 'Electrical', slug: 'electrical', description: 'Ignition coils, sensors, switches, and electrical components', display_order: 3 },
  { name: 'Suspension & Steering', slug: 'suspension-steering', description: 'Link rods, bushings, control arms, and steering parts', display_order: 4 },
  { name: 'Brakes', slug: 'brakes', description: 'Brake pads, rotors, calipers, and brake system components', display_order: 5 },
  { name: 'Interior', slug: 'interior', description: 'Seats, dashboard components, and interior accessories', display_order: 6 },
  { name: 'Exterior', slug: 'exterior', description: 'Lights, mirrors, grilles, and exterior accessories', display_order: 7 },
  { name: 'Maintenance', slug: 'maintenance', description: 'Belts, filters, fluids, and routine maintenance items', display_order: 8 },
];

export const productData = [
  // ENGINE PARTS (25 products)
  { categorySlug: 'engine-parts', name: 'Subaru Impreza STI Fuel Pump (2002-2007)', slug: 'subaru-impreza-sti-fuel-pump-2002-2007', description: 'High-performance fuel pump for Subaru Impreza STI. OEM quality for reliable fuel delivery.', price: '8500', compare_at_price: '10500', stock_quantity: 12, condition: 'new', sku: 'FP-SUBARU-STI-0207', images: getCloudinaryUrls(['2002-2007_Impreza_STI_fuel_pump.jpg']), is_featured: true, is_hot_deal: true, rating: '4.8', review_count: 23 },
  { categorySlug: 'engine-parts', name: 'Honda Fuel Pump Assembly', slug: 'honda-fuel-pump-assembly', description: 'Complete fuel pump assembly for various Honda models. Part number: 101961-7332.', price: '7200', stock_quantity: 8, condition: 'new', sku: 'FP-HONDA-101961', images: getCloudinaryUrls(['101961-7332_Fuel_pump_honda.png']), is_featured: true, rating: '4.6', review_count: 15 },
  { categorySlug: 'engine-parts', name: 'Subaru Timing Belt Kit', slug: 'subaru-timing-belt-kit', description: 'Premium timing belt for Subaru vehicles. Part number: 13028AA21B.', price: '4500', compare_at_price: '5500', stock_quantity: 20, condition: 'new', sku: 'TB-SUBARU-13028', images: getCloudinaryUrls(['13028AA21B_timing_belt.jpg']), is_featured: true, is_best_seller: true, rating: '4.9', review_count: 42 },
  { categorySlug: 'engine-parts', name: 'Mazda CX-5 Diesel Water Pump', slug: 'mazda-cx5-diesel-water-pump', description: 'OEM water pump for Mazda CX-5 diesel engines. Ensures optimal cooling performance.', price: '6800', stock_quantity: 10, condition: 'new', sku: 'WP-CX5-DIESEL', images: getCloudinaryUrls(['cx5_diesel_water_pump.jpg']), rating: '4.7', review_count: 18 },
  { categorySlug: 'engine-parts', name: '4PK 780 Drive Belt', slug: '4pk-780-drive-belt', description: 'High-quality drive belt suitable for various vehicle makes. 4PK 780 specification.', price: '1200', stock_quantity: 45, condition: 'new', sku: 'BELT-4PK-780', images: getCloudinaryUrls(['4PK_780_Belt.jpg']), is_hot_deal: true, rating: '4.5', review_count: 67 },
  { categorySlug: 'engine-parts', name: 'Honda Fit GD3 CVT Transmission Fluid', slug: 'honda-fit-gd3-cvt-fluid', description: 'Genuine CVT transmission fluid for Honda Fit GD3. Ensures smooth gear changes.', price: '2800', stock_quantity: 30, condition: 'new', sku: 'FLUID-FIT-CVT', images: getCloudinaryUrls(['Honda_Fit_GD3_CVTF_Gear_OIL.jpg']), rating: '4.8', review_count: 42 },
  { categorySlug: 'engine-parts', name: 'Nissan AC Pump Belt', slug: 'nissan-ac-pump-belt', description: 'AC compressor drive belt for Nissan vehicles. OEM quality replacement.', price: '950', stock_quantity: 25, condition: 'new', sku: 'BELT-NISSAN-AC', images: getCloudinaryUrls(['Ac_Pump_belt_Nissan.jpg']), rating: '4.4', review_count: 12 },
  { categorySlug: 'engine-parts', name: 'Toyota Crown Engine Computer ECU', slug: 'toyota-crown-ecu-89940-30160', description: 'Engine control unit for Toyota Crown. Part number: 89940-30160.', price: '15500', compare_at_price: '18000', stock_quantity: 3, condition: 'used', sku: 'ECU-CROWN-89940', images: getCloudinaryUrls(['COMPUTER_ASSY_039_89940-30160_toyota_Crown1.jpg']), is_best_seller: true, rating: '4.6', review_count: 8 },
  { categorySlug: 'engine-parts', name: 'Mazda Demio Engine Mount (2013)', slug: 'mazda-demio-2013-engine-mount', description: 'Heavy-duty engine mount for Mazda Demio 2013. Reduces vibration and noise.', price: '3400', stock_quantity: 15, condition: 'new', sku: 'MOUNT-DEMIO-2013', images: getCloudinaryUrls(['Madza_Demio_2013_engine_mount.jpg']), rating: '4.7', review_count: 22 },
  { categorySlug: 'engine-parts', name: 'Subaru Forester SJ5 Engine ECU', slug: 'subaru-forester-sj5-ecu', description: 'Engine computer for Subaru Forester SJ5. Tested and guaranteed working.', price: '18900', stock_quantity: 2, condition: 'used', sku: 'ECU-FORESTER-SJ5', images: getCloudinaryUrls(['COMPUTER_ECU_SJ5_Forester1.jpg']), rating: '4.9', review_count: 5 },
  { categorySlug: 'engine-parts', name: 'Toyota Sienta Engine Computer 89650-52012', slug: 'toyota-sienta-ecu-89650', description: 'OEM engine control unit for Toyota Sienta. Part number: 89650-52012.', price: '12800', compare_at_price: '15000', stock_quantity: 4, condition: 'used', sku: 'ECU-SIENTA-89650', images: getCloudinaryUrls(['Computer_for_Sienta_89650-52012.jpg']), is_hot_deal: true, rating: '4.5', review_count: 9 },
  { categorySlug: 'engine-parts', name: 'Honda 12290-RBJ-003 Engine Part', slug: 'honda-12290-rbj-003', description: 'Genuine Honda engine component. Part number: 12290-RBJ-003.', price: '4200', stock_quantity: 8, condition: 'new', sku: 'ENG-HONDA-12290', images: getCloudinaryUrls(['Honda_12290-RBJ-003.jpg']), rating: '4.6', review_count: 14 },
  { categorySlug: 'engine-parts', name: 'Nissan X-Trail DE Engine Computer', slug: 'nissan-xtrail-de-ecu', description: 'Engine control module for Nissan X-Trail DE models. Plug and play installation.', price: '14500', stock_quantity: 3, condition: 'used', sku: 'ECU-XTRAIL-DE', images: getCloudinaryUrls(['COMPUTER_ASSY_Nissan_Xtrail_DE.jpg']), rating: '4.7', review_count: 11 },
  { categorySlug: 'engine-parts', name: 'Toyota Air Cleaner for Swift', slug: 'toyota-air-cleaner-swift', description: 'High-flow air cleaner element. Compatible with Swift models.', price: '1800', stock_quantity: 35, condition: 'new', sku: 'AIR-SWIFT-001', images: getCloudinaryUrls(['Air_cleaner_for_swift.jpg']), rating: '4.4', review_count: 28 },
  { categorySlug: 'engine-parts', name: 'N-Wagon 2018 Air Cleaner', slug: 'n-wagon-2018-air-cleaner', description: 'OEM air cleaner for N-Wagon 2018. Ensures clean air intake for optimal performance.', price: '2100', stock_quantity: 18, condition: 'new', sku: 'AIR-NWAGON-18', images: getCloudinaryUrls(['air_cleaner_Nwagon_2018_small.png']), rating: '4.6', review_count: 15 },
  { categorySlug: 'engine-parts', name: 'ATF Transmission Oil Filter', slug: 'atf-transmission-oil-filter', description: 'Universal ATF oil filter for automatic transmissions. Premium quality.', price: '850', stock_quantity: 50, condition: 'new', sku: 'FILTER-ATF-001', images: getCloudinaryUrls(['ATF_Oil_Filter.jpg']), is_hot_deal: true, rating: '4.5', review_count: 89 },
  { categorySlug: 'engine-parts', name: 'ATF FZ Transmission Fluid', slug: 'atf-fz-transmission-fluid', description: 'Premium automatic transmission fluid. Suitable for most Japanese vehicles.', price: '3200', stock_quantity: 40, condition: 'new', sku: 'FLUID-ATF-FZ', images: getCloudinaryUrls(['atf_fz.jpg']), is_best_seller: true, rating: '4.8', review_count: 112 },
  { categorySlug: 'engine-parts', name: 'Toyota Power Steering Computer 89650-30831', slug: 'toyota-ps-computer-89650', description: 'Power steering control unit. Part number: 89650-30831.', price: '9800', stock_quantity: 5, condition: 'used', sku: 'PS-ECU-89650', images: getCloudinaryUrls(['COMPUTER_ASSY_POWER_STEERING_89650-30831.jpg']), rating: '4.7', review_count: 7 },
  { categorySlug: 'engine-parts', name: 'Toyota Crown Computer ECU 89243-30160', slug: 'toyota-crown-ecu-89243', description: 'Engine control unit for Toyota Crown 2008. Part number: 89243-30160.', price: '16200', compare_at_price: '19000', stock_quantity: 2, condition: 'used', sku: 'ECU-CROWN-89243', images: getCloudinaryUrls(['COMPUTER_ASSY_89243-30160_-_toyota_Crown_2008.jpg']), rating: '4.8', review_count: 6 },
  { categorySlug: 'engine-parts', name: 'Coil Spring Compressor Tool', slug: 'coil-spring-compressor-tool', description: 'Heavy-duty coil spring compressor for suspension work. Essential garage tool.', price: '4500', stock_quantity: 12, condition: 'new', sku: 'TOOL-SPRING-COMP', images: getCloudinaryUrls(['Coil_Spring_Compressor.jpg']), rating: '4.9', review_count: 34 },
  { categorySlug: 'engine-parts', name: 'Mazda Axela B62S Computer Module', slug: 'mazda-axela-b62s-computer', description: 'Engine control module for Mazda Axela. Part number: B62S66DT0.', price: '13500', stock_quantity: 4, condition: 'used', sku: 'ECU-AXELA-B62S', images: getCloudinaryUrls(['B62S66DT0_Axela_Computer.jpg']), rating: '4.6', review_count: 8 },
  { categorySlug: 'engine-parts', name: 'Mazda CX-5 Amplifier Computer CR-LM04J6JM', slug: 'mazda-cx5-amplifier-cr-lm04', description: 'Audio amplifier control unit for Mazda CX-5. Part number: CR-LM04J6JM.', price: '8900', stock_quantity: 6, condition: 'used', sku: 'AMP-CX5-CRLM04', images: getCloudinaryUrls(['COMPUTER_AMPLIFIER_CR-LM04J6JM_KA300_CX-5.jpg']), rating: '4.5', review_count: 12 },
  { categorySlug: 'engine-parts', name: 'Mazda Amplifier Computer CRLM63J0JM', slug: 'mazda-amplifier-crlm63', description: 'Audio system amplifier for Mazda vehicles. Excellent sound quality.', price: '7800', stock_quantity: 5, condition: 'used', sku: 'AMP-MAZDA-CRLM63', images: getCloudinaryUrls(['COMPUTER_AMPLIFIER_CRLM63J0JM.jpg']), rating: '4.6', review_count: 10 },
  { categorySlug: 'engine-parts', name: 'Mazda Axela BHP5 Audio Amplifier', slug: 'mazda-axela-bhp5-amplifier', description: 'Audio amplifier for Mazda Axela BHP5. Part number: 66 A20 BM.', price: '6500', stock_quantity: 7, condition: 'used', sku: 'AMP-AXELA-BHP5', images: getCloudinaryUrls(['AMPLIFIER_AUDIO_AXELA_BHP5_66_A20_BM.jpg']), rating: '4.4', review_count: 9 },
  { categorySlug: 'engine-parts', name: 'Honda Civic 2015 Ignition Coil', slug: 'honda-civic-2015-ignition-coil', description: 'OEM ignition coil for Honda Civic 2015. Ensures proper spark and engine performance.', price: '3800', stock_quantity: 14, condition: 'new', sku: 'IC-CIVIC-2015', images: getCloudinaryUrls(['Honda_Civic_2015_ignition_coil.jpg']), rating: '4.7', review_count: 26 },

  // BODY PARTS (20 products)
  { categorySlug: 'body-parts', name: 'Mazda CX-5 Front Bumper (2018)', slug: 'mazda-cx5-front-bumper-2018', description: 'OEM replacement front bumper for 2018 Mazda CX-5. Perfect fit and factory finish.', price: '18500', compare_at_price: '22000', stock_quantity: 3, condition: 'new', sku: 'BMP-MAZDA-CX5-18', images: getCloudinaryUrls(['2018_cx5_bumper.jpg']), is_featured: true, rating: '4.8', review_count: 6 },
  { categorySlug: 'body-parts', name: 'Mazda Axela Front Bumper', slug: 'mazda-axela-front-bumper', description: 'Complete front bumper assembly for Mazda Axela. Primed and ready to paint.', price: '16800', stock_quantity: 4, condition: 'used', sku: 'BMP-AXELA-001', images: getCloudinaryUrls(['axela_bumper.jpg']), rating: '4.5', review_count: 8 },
  { categorySlug: 'body-parts', name: 'Audi A6 Front Bumper', slug: 'audi-a6-front-bumper', description: 'OEM front bumper for Audi A6. Excellent condition, ready to install.', price: '28500', stock_quantity: 2, condition: 'used', sku: 'BMP-A6-FRONT', images: getCloudinaryUrls(['Audi_A6_Front_Bumper.png']), rating: '4.9', review_count: 4 },
  { categorySlug: 'body-parts', name: 'Audi A6 Front Fender Boot', slug: 'audi-a6-front-fender', description: 'Front fender panel for Audi A6. Factory quality replacement part.', price: '14500', stock_quantity: 3, condition: 'used', sku: 'FEND-A6-FRONT', images: getCloudinaryUrls(['Audi_A6_boot_Front_Fender.jpg']), rating: '4.6', review_count: 5 },
  { categorySlug: 'body-parts', name: 'Toyota Prado 2018 Body Kit Upgrade', slug: 'prado-2018-body-kit', description: 'Complete body kit upgrade for Toyota Land Cruiser Prado 2018. Transform your vehicle.', price: '85000', compare_at_price: '98000', stock_quantity: 1, condition: 'new', sku: 'KIT-PRADO-2018', images: getCloudinaryUrls(['Body_Kit_Upgrade_prado_2018.jpg']), is_hot_deal: true, is_best_seller: true, rating: '5.0', review_count: 3 },
  { categorySlug: 'body-parts', name: 'Allion 260 Nose Cut Assembly', slug: 'allion-260-nose-cut', description: 'Complete front nose cut for Toyota Allion 260. Includes headlights and grille.', price: '45000', stock_quantity: 2, condition: 'used', sku: 'NOSE-ALLION-260', images: getCloudinaryUrls(['Allion_260_nose_cut.jpg']), rating: '4.7', review_count: 6 },
  { categorySlug: 'body-parts', name: 'Mazda 2014 Axela Foglight Cover', slug: 'mazda-2014-axela-foglight-cover', description: 'Fog light cover for Mazda Axela 2014. Perfect OEM fit.', price: '1200', stock_quantity: 12, condition: 'new', sku: 'FOG-AXELA-14', images: getCloudinaryUrls(['2014_axela_foglight_cover.jpg']), rating: '4.5', review_count: 18 },
  { categorySlug: 'body-parts', name: 'Mazda CX-5 2018 Foglight Cover', slug: 'mazda-cx5-2018-foglight-cover', description: 'Fog lamp cover for CX-5 2018. Left and right available.', price: '1500', stock_quantity: 20, condition: 'new', sku: 'FOG-CX5-18', images: getCloudinaryUrls(['cx-5_2018_foglamp_cover.jpg']), rating: '4.6', review_count: 24 },
  { categorySlug: 'body-parts', name: 'Mazda CX-5 Fog Light Covers (Pair)', slug: 'mazda-cx5-foglight-covers-pair', description: 'Pair of fog light covers for CX-5. Premium quality plastic.', price: '2400', stock_quantity: 15, condition: 'new', sku: 'FOG-CX5-PAIR', images: getCloudinaryUrls(['cx5_foglight_covers.jpg']), is_hot_deal: true, rating: '4.7', review_count: 31 },
  { categorySlug: 'body-parts', name: 'Mazda CX-5 2018 Front Grille', slug: 'mazda-cx5-2018-grille', description: 'Chrome front grille for Mazda CX-5 2018. Adds premium look to your vehicle.', price: '8500', stock_quantity: 8, condition: 'new', sku: 'GRILL-CX5-18', images: getCloudinaryUrls(['cx5_2018_grille.jpg']), rating: '4.8', review_count: 22 },
  { categorySlug: 'body-parts', name: 'Mazda CX-5 Mud Flaps Set', slug: 'mazda-cx5-mudflaps', description: 'Complete set of mud flaps for CX-5. Protects paint from road debris.', price: '3200', stock_quantity: 25, condition: 'new', sku: 'MUD-CX5-SET', images: getCloudinaryUrls(['cx5_mudflaps.jpg']), rating: '4.5', review_count: 45 },
  { categorySlug: 'body-parts', name: 'Land Cruiser Prado J150 Side Steps', slug: 'prado-j150-side-steps', description: 'Premium side step kit for Land Cruiser Prado J150. Easy installation.', price: '24500', compare_at_price: '28000', stock_quantity: 5, condition: 'new', sku: 'STEP-PRADO-J150', images: getCloudinaryUrls(['Land_Cruiser_Prado_J150_side_step_kit.jpg']), is_best_seller: true, rating: '4.9', review_count: 19 },
  { categorySlug: 'body-parts', name: 'Audi A4 Stone Guard', slug: 'audi-a4-stone-guard', description: 'Underbody stone guard for Audi A4. Protects against road debris damage.', price: '4500', stock_quantity: 10, condition: 'new', sku: 'GUARD-A4-STONE', images: getCloudinaryUrls(['Audi_A4_stone_guard.jpg']), rating: '4.6', review_count: 14 },
  { categorySlug: 'body-parts', name: 'Lexus 350H Stone Guard Left', slug: 'lexus-350h-stone-guard-lh', description: 'Left-hand stone guard for Lexus 350H. OEM quality protection.', price: '5200', stock_quantity: 6, condition: 'new', sku: 'GUARD-LEX350-LH', images: getCloudinaryUrls(['Lexus_350_H_stone_guard_lh.png']), rating: '4.7', review_count: 9 },
  { categorySlug: 'body-parts', name: 'Generic Front Bumper', slug: 'generic-front-bumper', description: 'Universal front bumper suitable for various models. Good condition.', price: '12000', stock_quantity: 4, condition: 'used', sku: 'BMP-GENERIC-001', images: getCloudinaryUrls(['BUMPER.jpg']), rating: '4.3', review_count: 11 },
  { categorySlug: 'body-parts', name: 'Corolla NZE Rear Lamp', slug: 'corolla-nze-rear-lamp', description: 'Tail light assembly for Toyota Corolla NZE. Crystal clear lens.', price: '4800', stock_quantity: 12, condition: 'used', sku: 'TAIL-COROLLA-NZE', images: getCloudinaryUrls(['Corolla_Nze_rear_lamp.jpg']), rating: '4.5', review_count: 16 },
  { categorySlug: 'body-parts', name: 'Toyota Axio Dashboard', slug: 'toyota-axio-dashboard', description: 'Complete dashboard assembly for Toyota Axio. Excellent condition.', price: '18500', stock_quantity: 2, condition: 'used', sku: 'DASH-AXIO-001', images: getCloudinaryUrls(['Axio_dashboard.jpg']), rating: '4.6', review_count: 5 },
  { categorySlug: 'body-parts', name: 'Toyota Axio 161 Side Mirror', slug: 'toyota-axio-161-side-mirror', description: 'Side door mirror for Toyota Axio 161. Power adjustable.', price: '5500', stock_quantity: 8, condition: 'used', sku: 'MIR-AXIO-161', images: getCloudinaryUrls(['Axio_161_Side_mirror.jpg']), rating: '4.4', review_count: 12 },
  { categorySlug: 'body-parts', name: 'Honda RE4 Bonnet Mirror', slug: 'honda-re4-bonnet-mirror', description: 'Bonnet-mounted mirror for Honda RE4. Good working condition.', price: '3200', stock_quantity: 6, condition: 'used', sku: 'MIR-RE4-BONNET', images: getCloudinaryUrls(['honda_Re4_bonnet_mirror.jpg']), rating: '4.3', review_count: 8 },
  { categorySlug: 'body-parts', name: 'Mazda CX-5 Side Mirror', slug: 'mazda-cx5-side-mirror', description: 'Complete side mirror assembly for Mazda CX-5. Power and heated.', price: '7800', stock_quantity: 10, condition: 'new', sku: 'MIR-CX5-SIDE', images: getCloudinaryUrls(['cx5_mirror.jpg']), rating: '4.7', review_count: 20 },

  // ELECTRICAL (30 products)
  { categorySlug: 'electrical', name: 'Suzuki Grand Vitara Ignition Coil', slug: 'suzuki-grand-vitara-ignition-coil', description: 'High-quality ignition coil for Suzuki Grand Vitara. Part number: 33400-51K20.', price: '3200', stock_quantity: 15, condition: 'new', sku: 'IC-SUZUKI-33400', images: getCloudinaryUrls(['33400-51K20_Grand_vitara_ignition_coil.jpg']), is_featured: true, rating: '4.5', review_count: 12 },
  { categorySlug: 'electrical', name: 'Toyota Ignition Coil 90919-02252', slug: 'toyota-ignition-coil-90919-02252', description: 'OEM ignition coil for various Toyota models. Part number: 90919-02252.', price: '3500', stock_quantity: 22, condition: 'new', sku: 'IC-TOY-90919-02252', images: getCloudinaryUrls(['ignition_coil_90919-02252.png']), is_hot_deal: true, rating: '4.8', review_count: 38 },
  { categorySlug: 'electrical', name: 'Toyota Ignition Coil 90919-01243', slug: 'toyota-ignition-coil-90919-01243', description: 'Genuine Toyota ignition coil. Part number: 90919-01243.', price: '3400', stock_quantity: 18, condition: 'new', sku: 'IC-TOY-01243', images: getCloudinaryUrls(['90919-01243.jpg']), rating: '4.7', review_count: 29 },
  { categorySlug: 'electrical', name: 'Toyota Ignition Coil 90919-01247', slug: 'toyota-ignition-coil-90919-01247', description: 'High-performance ignition coil. Part number: 90919-01247.', price: '3600', stock_quantity: 16, condition: 'new', sku: 'IC-TOY-01247', images: getCloudinaryUrls(['90919-01247.jpg']), rating: '4.6', review_count: 24 },
  { categorySlug: 'electrical', name: 'ABS Wheel Speed Sensor', slug: 'abs-wheel-speed-sensor', description: 'Universal ABS sensor compatible with various makes. Reliable performance.', price: '2800', stock_quantity: 35, condition: 'new', sku: 'SENS-ABS-001', images: getCloudinaryUrls(['ABS_sensor.jpg']), is_hot_deal: true, rating: '4.5', review_count: 56 },
  { categorySlug: 'electrical', name: 'Toyota Acceleration Sensor', slug: 'toyota-acceleration-sensor', description: 'Throttle position sensor for Toyota vehicles. Ensures smooth acceleration.', price: '4200', stock_quantity: 12, condition: 'new', sku: 'SENS-TOY-ACCEL', images: getCloudinaryUrls(['Acceleration_sensor_Toyota.jpg']), rating: '4.7', review_count: 21 },
  { categorySlug: 'electrical', name: 'Mazda CX-5 Air Flow Sensor', slug: 'mazda-cx5-air-flow-sensor', description: 'MAF sensor for Mazda CX-5. Accurate air measurement for optimal performance.', price: '8500', stock_quantity: 8, condition: 'new', sku: 'SENS-CX5-MAF', images: getCloudinaryUrls(['Aif_Flow_sensor_mazda_Cx-5.jpg']), rating: '4.8', review_count: 15 },
  { categorySlug: 'electrical', name: 'Lexus RX 450H Air Sensor', slug: 'lexus-rx-450h-air-sensor', description: 'Air flow sensor for Lexus RX 450H hybrid. Precision calibrated.', price: '12500', stock_quantity: 5, condition: 'new', sku: 'SENS-RX450-AIR', images: getCloudinaryUrls(['Air_sensor_RX_450H.jpg']), is_best_seller: true, rating: '4.9', review_count: 11 },
  { categorySlug: 'electrical', name: 'Toyota Caldina Oxygen Sensor 89465-20270', slug: 'toyota-caldina-oxygen-sensor', description: 'O2 sensor for Toyota Caldina. Part number: 89465-20270.', price: '6800', stock_quantity: 10, condition: 'new', sku: 'SENS-CALDINA-O2', images: getCloudinaryUrls(['89465-20270_Caldina_oxygen_sensor.jpg']), rating: '4.6', review_count: 18 },
  { categorySlug: 'electrical', name: 'Nissan Note Angle Sensor', slug: 'nissan-note-angle-sensor', description: 'Steering angle sensor for Nissan Note. Essential for stability control.', price: '7200', stock_quantity: 9, condition: 'new', sku: 'SENS-NOTE-ANGLE', images: getCloudinaryUrls(['Angle_sensor_Nissan_Note.jpg']), rating: '4.5', review_count: 13 },
  { categorySlug: 'electrical', name: 'Nissan X-Trail ARB Bushings Sensor', slug: 'nissan-xtrail-arb-sensor', description: 'Anti-roll bar sensor for Nissan X-Trail. Improves handling response.', price: '5500', stock_quantity: 11, condition: 'new', sku: 'SENS-XTRAIL-ARB', images: getCloudinaryUrls(['Arb_Bushes_nissan_Xtrail.jpg']), rating: '4.4', review_count: 16 },
  { categorySlug: 'electrical', name: 'Mazda CX-5 BCM Body Control Module', slug: 'mazda-cx5-bcm', description: 'Body control module for Mazda CX-5. Controls all electrical systems.', price: '15800', stock_quantity: 4, condition: 'used', sku: 'BCM-CX5-001', images: getCloudinaryUrls(['BCM_for_Mazda_CX5.jpg']), rating: '4.7', review_count: 9 },
  { categorySlug: 'electrical', name: 'Audi A6 BCM Module', slug: 'audi-a6-bcm', description: 'Body control module for Audi A6. Tested and working perfectly.', price: '18500', stock_quantity: 3, condition: 'used', sku: 'BCM-A6-001', images: getCloudinaryUrls(['Audi_A6_BCM.jpg']), rating: '4.8', review_count: 6 },
  { categorySlug: 'electrical', name: 'Nissan Serena Camera Control ECU', slug: 'nissan-serena-camera-ecu', description: 'Rear camera control unit for Nissan Serena. Crystal clear display.', price: '9800', stock_quantity: 6, condition: 'used', sku: 'CAM-SERENA-ECU', images: getCloudinaryUrls(['Camera_Control_ECU_Nissan_Serena.jpg']), rating: '4.6', review_count: 12 },
  { categorySlug: 'electrical', name: 'Mazda Demio Camera Unit', slug: 'mazda-demio-camera-unit', description: 'Backup camera module for Mazda Demio. Easy installation.', price: '7500', stock_quantity: 8, condition: 'used', sku: 'CAM-DEMIO-001', images: getCloudinaryUrls(['Camera_Unit_Mazda_demio.jpg']), rating: '4.5', review_count: 14 },
  { categorySlug: 'electrical', name: 'C6 H11 LED Bulbs', slug: 'c6-h11-led-bulbs', description: 'High-brightness LED headlight bulbs. H11 socket, 6000K white light.', price: '4500', compare_at_price: '5500', stock_quantity: 45, condition: 'new', sku: 'LED-H11-C6', images: getCloudinaryUrls(['C6_H11_LED_Bulbs.jpg']), is_hot_deal: true, is_best_seller: true, rating: '4.9', review_count: 134 },
  { categorySlug: 'electrical', name: 'Audi A3 Combination Switch', slug: 'audi-a3-combination-switch', description: 'Multi-function steering column switch for Audi A3.', price: '6800', stock_quantity: 7, condition: 'used', sku: 'SW-A3-COMB', images: getCloudinaryUrls(['Audi_A3_Combination_Swtich.jpg']), rating: '4.6', review_count: 10 },
  { categorySlug: 'electrical', name: 'Ignition Start Button', slug: 'ignition-start-button', description: 'Push-button ignition start system. Universal fit for most modern vehicles.', price: '3200', stock_quantity: 20, condition: 'new', sku: 'IGN-BUTTON-001', images: getCloudinaryUrls(['ignition_strat_button.jpg']), rating: '4.4', review_count: 28 },
  { categorySlug: 'electrical', name: 'Toyota Allion Ignition Switch', slug: 'toyota-allion-ignition-switch', description: 'Key ignition switch for Toyota Allion. OEM replacement.', price: '4500', stock_quantity: 12, condition: 'new', sku: 'IGN-ALLION-001', images: getCloudinaryUrls(['Ignition_switch_Allion.jpg']), rating: '4.7', review_count: 19 },
  { categorySlug: 'electrical', name: 'Suzuki Keyless Door Receiver', slug: 'suzuki-keyless-receiver', description: 'Keyless entry receiver module for Suzuki vehicles.', price: '5800', stock_quantity: 9, condition: 'new', sku: 'KEY-SUZ-RECEIVER', images: getCloudinaryUrls(['Keyless_door_receiver_suzuki.jpg']), rating: '4.5', review_count: 15 },
  { categorySlug: 'electrical', name: 'Mazda CX-5 Keyless Receiver', slug: 'mazda-cx5-keyless-receiver', description: 'Keyless entry receiver for Mazda CX-5. Plug and play installation.', price: '6200', stock_quantity: 8, condition: 'new', sku: 'KEY-CX5-RECEIVER', images: getCloudinaryUrls(['KeyLess_Receiver_Mazda_Cx5.jpg']), rating: '4.6', review_count: 17 },
  { categorySlug: 'electrical', name: 'Mazda Axela Immobilizer Module', slug: 'mazda-axela-immobilizer', description: 'Anti-theft immobilizer module for Mazda Axela. Security system essential.', price: '8500', stock_quantity: 5, condition: 'used', sku: 'IMM-AXELA-001', images: getCloudinaryUrls(['Immobolizer_module_for_Mazda_Axela.jpg']), rating: '4.7', review_count: 11 },
  { categorySlug: 'electrical', name: 'Mazda CX-3 Control Unit', slug: 'mazda-cx3-control-unit', description: 'Electronic control unit for Mazda CX-3. Various functions control.', price: '11500', stock_quantity: 4, condition: 'used', sku: 'ECU-CX3-CTRL', images: getCloudinaryUrls(['Control_Unit_for_Mazda_Cx3.jpg']), rating: '4.6', review_count: 8 },
  { categorySlug: 'electrical', name: 'Suzuki Swift Control Unit', slug: 'suzuki-swift-control-unit', description: 'Control module for Suzuki Swift. Tested and guaranteed working.', price: '9800', stock_quantity: 6, condition: 'used', sku: 'ECU-SWIFT-CTRL', images: getCloudinaryUrls(['Control_Unit_for_swift.jpg']), rating: '4.5', review_count: 10 },
  { categorySlug: 'electrical', name: 'Nissan Note Control Unit 31036-JX00C', slug: 'nissan-note-control-unit', description: 'Control unit for Nissan Note/Vanette. Part number: 31036-JX00C.', price: '10500', stock_quantity: 5, condition: 'used', sku: 'ECU-NOTE-31036', images: getCloudinaryUrls(['CONTROL_UNIT_NOTE_Vannete_31036_JX00C.jpg']), rating: '4.6', review_count: 9 },
  { categorySlug: 'electrical', name: 'Toyota Crown Telematics Transceiver 86741-30040', slug: 'toyota-crown-telematics', description: 'Telematics communication module for Toyota Crown. Part number: 86741-30040.', price: '12800', stock_quantity: 3, condition: 'used', sku: 'TEL-CROWN-86741', images: getCloudinaryUrls(['CROWN_TRANSCIEVER%2C_TELEMATICS_86741-30040.jpg']), rating: '4.7', review_count: 5 },
  { categorySlug: 'electrical', name: 'Honda Vezel Accessories Control Computer', slug: 'honda-vezel-accessories-computer', description: 'Accessories control module for Honda Vezel. Manages power accessories.', price: '13500', stock_quantity: 4, condition: 'used', sku: 'ACC-VEZEL-CTRL', images: getCloudinaryUrls(['Honda_Vezel_Accessories_control_Computer.jpg']), rating: '4.8', review_count: 7 },
  { categorySlug: 'electrical', name: 'Honda Vezel Power Steering Computer', slug: 'honda-vezel-ps-computer', description: 'Electric power steering control unit for Honda Vezel.', price: '16500', stock_quantity: 3, condition: 'used', sku: 'PS-VEZEL-ECU', images: getCloudinaryUrls(['hONDA_VEZEL_power_steering_compuer.jpg']), rating: '4.9', review_count: 6 },
  { categorySlug: 'electrical', name: 'AZR60 Noah Wheel Sensor Spiral', slug: 'azr60-noah-wheel-sensor', description: 'ABS wheel sensor spiral cable for Toyota Noah AZR60.', price: '3800', stock_quantity: 10, condition: 'new', sku: 'SENS-NOAH-SPIRAL', images: getCloudinaryUrls(['AZR60_Noah_Wheel_Sensor_Spiral.jpg']), rating: '4.5', review_count: 14 },
  { categorySlug: 'electrical', name: 'Mazda CX-5 Wheel Spiral Sensor (2013 Diesel)', slug: 'mazda-cx5-wheel-spiral-2013', description: 'Wheel speed sensor spiral for Mazda CX-5 2013 diesel model.', price: '4200', stock_quantity: 8, condition: 'new', sku: 'SENS-CX5-SPIRAL', images: getCloudinaryUrls(['CX-5_Wheel_Spiral_2013_Diesel.jpg']), rating: '4.6', review_count: 12 },

  // SUSPENSION & STEERING (20 products)
  { categorySlug: 'suspension-steering', name: 'Toyota Auris Link Rod 48820-47020', slug: 'toyota-auris-link-rod', description: 'Front stabilizer link for Toyota Auris. Part number: 48820-47020.', price: '2800', stock_quantity: 18, condition: 'new', sku: 'LINK-AURIS-48820', images: getCloudinaryUrls(['48820-47020_Auris_linkg1.jpg']), rating: '4.7', review_count: 24 },
  { categorySlug: 'suspension-steering', name: 'Honda CRV Link Assembly', slug: 'honda-crv-link-assembly', description: 'Stabilizer link assembly for Honda CRV. Heavy-duty construction.', price: '3200', stock_quantity: 15, condition: 'new', sku: 'LINK-CRV-001', images: getCloudinaryUrls(['CRV_link_Assy.jpg']), is_hot_deal: true, rating: '4.8', review_count: 31 },
  { categorySlug: 'suspension-steering', name: 'Honda RD4 Link Rod', slug: 'honda-rd4-link-rod', description: 'Front suspension link for Honda RD4. Quality aftermarket part.', price: '2900', stock_quantity: 20, condition: 'new', sku: 'LINK-RD4-001', images: getCloudinaryUrls(['Honda_RD4_link2.jpg']), rating: '4.6', review_count: 28 },
  { categorySlug: 'suspension-steering', name: 'Mazda CX-5 Tie Rod KD3132240B', slug: 'mazda-cx5-tie-rod', description: 'Steering tie rod for Mazda CX-5. Part number: KD3132240B.', price: '4500', stock_quantity: 12, condition: 'new', sku: 'TIE-CX5-KD313', images: getCloudinaryUrls(['KD3132240B_Mazda_cx5_tie_rod.png']), is_best_seller: true, rating: '4.9', review_count: 35 },
  { categorySlug: 'suspension-steering', name: 'Generic Link Rod Type 2', slug: 'generic-link-rod-2', description: 'Universal stabilizer link suitable for various models. Quality construction.', price: '2400', stock_quantity: 35, condition: 'new', sku: 'LINK-GENERIC-002', images: getCloudinaryUrls(['Link2.png']), rating: '4.4', review_count: 52 },
  { categorySlug: 'suspension-steering', name: 'Anti-Roll Bar Bushings', slug: 'arb-bushings-set', description: 'Heavy-duty ARB bushings. Reduces body roll and improves handling.', price: '1800', stock_quantity: 40, condition: 'new', sku: 'BUSH-ARB-001', images: getCloudinaryUrls(['bushes.jpg']), is_hot_deal: true, rating: '4.5', review_count: 67 },
  { categorySlug: 'suspension-steering', name: 'Aluminium Knuckle Arm', slug: 'aluminium-knuckle-arm', description: 'Lightweight aluminium steering knuckle arm. Performance upgrade.', price: '8500', stock_quantity: 8, condition: 'new', sku: 'KNUCKLE-ALU-001', images: getCloudinaryUrls(['Aluminium_Knuckle_Arm.jpg']), rating: '4.7', review_count: 16 },
  { categorySlug: 'suspension-steering', name: 'Ball Joint Set', slug: 'ball-joint-set', description: 'Upper and lower ball joints. Universal fit for most Japanese vehicles.', price: '4200', stock_quantity: 22, condition: 'new', sku: 'BALL-JOINT-SET', images: getCloudinaryUrls(['bLL4.jpg']), rating: '4.6', review_count: 41 },
  { categorySlug: 'suspension-steering', name: 'Tie Rod End Left', slug: 'tie-rod-end-left', description: 'Left-hand tie rod end. Precision machined for accurate steering.', price: '2200', stock_quantity: 25, condition: 'new', sku: 'TIE-END-LEFT', images: getCloudinaryUrls(['koy1-33-48za.jpg']), rating: '4.5', review_count: 33 },
  { categorySlug: 'suspension-steering', name: 'Suspension Bushing Kit', slug: 'suspension-bushing-kit', description: 'Complete suspension bushing replacement kit. Restores like-new feel.', price: '5800', stock_quantity: 18, condition: 'new', sku: 'BUSH-KIT-001', images: getCloudinaryUrls(['aas.jpg']), rating: '4.7', review_count: 29 },
  { categorySlug: 'suspension-steering', name: 'Shock Absorber Front', slug: 'shock-absorber-front', description: 'Front shock absorber. Gas-charged for superior damping.', price: '6500', stock_quantity: 16, condition: 'new', sku: 'SHOCK-FRONT-001', images: getCloudinaryUrls(['access.png']), rating: '4.8', review_count: 37 },
  { categorySlug: 'suspension-steering', name: 'Shock Absorber Rear', slug: 'shock-absorber-rear', description: 'Rear shock absorber. Improves ride comfort and handling.', price: '6200', stock_quantity: 16, condition: 'new', sku: 'SHOCK-REAR-001', images: getCloudinaryUrls(['K9.jpg']), rating: '4.7', review_count: 34 },
  { categorySlug: 'suspension-steering', name: 'Control Arm Lower Front', slug: 'control-arm-lower-front', description: 'Lower front control arm. Heavy-duty construction for durability.', price: '7800', stock_quantity: 10, condition: 'new', sku: 'ARM-LOWER-FRONT', images: getCloudinaryUrls(['22401-JD01B.jpg']), rating: '4.6', review_count: 22 },
  { categorySlug: 'suspension-steering', name: 'Control Arm Upper Front', slug: 'control-arm-upper-front', description: 'Upper front control arm with ball joint. Complete assembly.', price: '8200', stock_quantity: 10, condition: 'new', sku: 'ARM-UPPER-FRONT', images: getCloudinaryUrls(['16546-30P00e.jpg']), rating: '4.7', review_count: 20 },
  { categorySlug: 'suspension-steering', name: 'Sway Bar Link Front', slug: 'sway-bar-link-front', description: 'Front sway bar end link. Reduces body roll in corners.', price: '2600', stock_quantity: 28, condition: 'new', sku: 'SWAY-LINK-FRONT', images: getCloudinaryUrls(['31d-6IkjYAL__SL500_AC_SS350_.jpg']), rating: '4.5', review_count: 45 },
  { categorySlug: 'suspension-steering', name: 'Sway Bar Link Rear', slug: 'sway-bar-link-rear', description: 'Rear sway bar link. Improves stability and handling.', price: '2600', stock_quantity: 28, condition: 'new', sku: 'SWAY-LINK-REAR', images: getCloudinaryUrls(['honda.png']), rating: '4.5', review_count: 42 },
  { categorySlug: 'suspension-steering', name: 'Strut Mount Front', slug: 'strut-mount-front', description: 'Front strut mount bearing. Eliminates noise and improves steering feel.', price: '3400', stock_quantity: 20, condition: 'new', sku: 'MOUNT-STRUT-FRONT', images: getCloudinaryUrls(['isuzu.png']), rating: '4.6', review_count: 38 },
  { categorySlug: 'suspension-steering', name: 'Strut Mount Rear', slug: 'strut-mount-rear', description: 'Rear strut mount assembly. Reduces road noise transmission.', price: '3200', stock_quantity: 20, condition: 'new', sku: 'MOUNT-STRUT-REAR', images: getCloudinaryUrls(['bmw.png']), rating: '4.5', review_count: 35 },
  { categorySlug: 'suspension-steering', name: 'Wheel Bearing Front Hub', slug: 'wheel-bearing-front-hub', description: 'Front wheel hub bearing assembly. Sealed for long life.', price: '5500', stock_quantity: 15, condition: 'new', sku: 'BEARING-HUB-FRONT', images: getCloudinaryUrls(['benz.png']), rating: '4.8', review_count: 41 },
  { categorySlug: 'suspension-steering', name: 'Wheel Bearing Rear Hub', slug: 'wheel-bearing-rear-hub', description: 'Rear wheel hub bearing assembly. Pre-greased and sealed.', price: '5200', stock_quantity: 15, condition: 'new', sku: 'BEARING-HUB-REAR', images: getCloudinaryUrls(['care.png']), rating: '4.7', review_count: 39 },

  // BRAKES (15 products)
  { categorySlug: 'brakes', name: 'Toyota/Lexus Brake Pad Set 04465-42200', slug: 'toyota-lexus-brake-pad-set', description: 'Premium brake pads for Toyota and Lexus. Part number: 04465-42200.', price: '5500', compare_at_price: '6800', stock_quantity: 18, condition: 'new', sku: 'BP-TOYOTA-04465', images: getCloudinaryUrls(['04465-42200br.jpg', '04465-42200rae.jpg']), is_featured: true, is_hot_deal: true, rating: '4.9', review_count: 56 },
  { categorySlug: 'brakes', name: 'Subaru Brake Pad 26296AG051', slug: 'subaru-brake-pad-26296ag051', description: 'OEM brake pad for Subaru 2007 models. Part number: 26296AG051.', price: '4800', stock_quantity: 15, condition: 'new', sku: 'BP-SUBARU-26296', images: getCloudinaryUrls(['Brake_pd_26296AG051_2007.jpg']), rating: '4.7', review_count: 32 },
  { categorySlug: 'brakes', name: 'Generic Brake Pad Set 30330', slug: 'generic-brake-pad-30330', description: 'Universal brake pads suitable for various models. Good quality aftermarket.', price: '3500', stock_quantity: 35, condition: 'new', sku: 'BP-GENERIC-30330', images: getCloudinaryUrls(['brake30330%2B1.jpg']), is_hot_deal: true, rating: '4.4', review_count: 78 },
  { categorySlug: 'brakes', name: 'Textar Premium Brake Pads', slug: 'textar-premium-brake-pads', description: 'European quality Textar brake pads. Low dust formula, excellent stopping power.', price: '6200', compare_at_price: '7500', stock_quantity: 22, condition: 'new', sku: 'BP-TEXTAR-PREM', images: getCloudinaryUrls(['Brakepad_textar.jpg']), is_best_seller: true, rating: '4.9', review_count: 91 },
  { categorySlug: 'brakes', name: 'Lexus LX570 Brake Pad', slug: 'lexus-lx570-brake-pad', description: 'Heavy-duty brake pads for Lexus LX570. Designed for large SUVs.', price: '8500', stock_quantity: 8, condition: 'new', sku: 'BP-LX570-001', images: getCloudinaryUrls(['Lexus_LX570_Brake_pad.jpg']), rating: '4.8', review_count: 18 },
  { categorySlug: 'brakes', name: 'Brake Rotor Front Pair', slug: 'brake-rotor-front-pair', description: 'Front brake disc rotors. Vented design for better heat dissipation.', price: '7800', stock_quantity: 20, condition: 'new', sku: 'ROTOR-FRONT-PAIR', images: getCloudinaryUrls(['items.png']), rating: '4.6', review_count: 44 },
  { categorySlug: 'brakes', name: 'Brake Rotor Rear Pair', slug: 'brake-rotor-rear-pair', description: 'Rear brake disc rotors. Balanced and tested for smooth braking.', price: '7200', stock_quantity: 20, condition: 'new', sku: 'ROTOR-REAR-PAIR', images: getCloudinaryUrls(['items2.png']), rating: '4.6', review_count: 41 },
  { categorySlug: 'brakes', name: 'Brake Caliper Front Left', slug: 'brake-caliper-front-left', description: 'Front left brake caliper. Remanufactured to OEM standards.', price: '8500', stock_quantity: 8, condition: 'new', sku: 'CAL-FRONT-LEFT', images: getCloudinaryUrls(['bike.png']), rating: '4.7', review_count: 26 },
  { categorySlug: 'brakes', name: 'Brake Caliper Front Right', slug: 'brake-caliper-front-right', description: 'Front right brake caliper. Includes hardware and lubricant.', price: '8500', stock_quantity: 8, condition: 'new', sku: 'CAL-FRONT-RIGHT', images: getCloudinaryUrls(['hot.png']), rating: '4.7', review_count: 25 },
  { categorySlug: 'brakes', name: 'Brake Caliper Rear Left', slug: 'brake-caliper-rear-left', description: 'Rear left brake caliper with parking brake mechanism.', price: '9200', stock_quantity: 6, condition: 'new', sku: 'CAL-REAR-LEFT', images: getCloudinaryUrls(['lexus.png']), rating: '4.6', review_count: 19 },
  { categorySlug: 'brakes', name: 'Brake Caliper Rear Right', slug: 'brake-caliper-rear-right', description: 'Rear right brake caliper. Parking brake integrated.', price: '9200', stock_quantity: 6, condition: 'new', sku: 'CAL-REAR-RIGHT', images: getCloudinaryUrls(['lc300.jpg']), rating: '4.6', review_count: 18 },
  { categorySlug: 'brakes', name: 'Brake Master Cylinder', slug: 'brake-master-cylinder', description: 'Master brake cylinder. Ensures consistent pedal feel and pressure.', price: '12500', stock_quantity: 10, condition: 'new', sku: 'MASTER-CYL-001', images: getCloudinaryUrls(['Lense_cover.jpg']), rating: '4.8', review_count: 31 },
  { categorySlug: 'brakes', name: 'Brake Booster Vacuum', slug: 'brake-booster-vacuum', description: 'Vacuum brake booster. Provides power assistance for easier braking.', price: '15500', stock_quantity: 7, condition: 'new', sku: 'BOOSTER-VAC-001', images: getCloudinaryUrls(['Images_for_site_colloara_2008.jpg']), rating: '4.7', review_count: 22 },
  { categorySlug: 'brakes', name: 'ABS Control Module', slug: 'abs-control-module', description: 'ABS control unit. Prevents wheel lockup during hard braking.', price: '18500', stock_quantity: 5, condition: 'used', sku: 'ABS-MODULE-001', images: getCloudinaryUrls(['IMG_20190204_124642.jpg']), rating: '4.6', review_count: 14 },
  { categorySlug: 'brakes', name: 'Brake Fluid DOT 4', slug: 'brake-fluid-dot4', description: 'High-performance DOT 4 brake fluid. 500ml bottle.', price: '800', stock_quantity: 60, condition: 'new', sku: 'FLUID-BRAKE-DOT4', images: getCloudinaryUrls(['atf21.png']), is_hot_deal: true, rating: '4.7', review_count: 156 },

  // INTERIOR (10 products)
  { categorySlug: 'interior', name: 'Toyota Axio 2010 Xenon Headlights', slug: 'toyota-axio-2010-xenon-headlights', description: 'Premium xenon headlight set for Toyota Axio 2010. Bright white light output.', price: '28500', compare_at_price: '32000', stock_quantity: 3, condition: 'used', sku: 'HEAD-AXIO-XENON', images: getCloudinaryUrls(['Axio_2010_Xenon_Headlights.jpg']), is_best_seller: true, rating: '4.9', review_count: 11 },
  { categorySlug: 'interior', name: 'Honda CRV RE4 Driver Air Bag', slug: 'honda-crv-re4-driver-airbag', description: 'Driver side airbag for Honda CRV RE4. Safety critical component.', price: '8500', stock_quantity: 5, condition: 'used', sku: 'AIR-CRV-DRIVER', images: getCloudinaryUrls(['Honda_CRV_RE4_Driver_Air_Bag.jpg']), rating: '4.6', review_count: 8 },
  { categorySlug: 'interior', name: 'Steering Wheel Leather Wrap', slug: 'steering-wheel-leather-wrap', description: 'Premium leather steering wheel cover. Universal fit, easy installation.', price: '1200', stock_quantity: 45, condition: 'new', sku: 'INT-STEER-LEATHER', images: getCloudinaryUrls(['IMG_20190204_1246421.jpg']), is_hot_deal: true, rating: '4.5', review_count: 87 },
  { categorySlug: 'interior', name: 'Car Floor Mat Set (5 pieces)', slug: 'car-floor-mat-set-5pc', description: 'Universal car floor mats. Heavy-duty rubber, all-weather protection.', price: '2800', stock_quantity: 35, condition: 'new', sku: 'INT-MAT-5PC', images: getCloudinaryUrls(['IMG_20190204_124738.jpg']), rating: '4.6', review_count: 102 },
  { categorySlug: 'interior', name: 'Dashboard Camera HD', slug: 'dashboard-camera-hd', description: 'Full HD dashboard camera with night vision. Loop recording.', price: '5500', stock_quantity: 28, condition: 'new', sku: 'INT-DASHCAM-HD', images: getCloudinaryUrls(['IMG_20190204_124828.jpg']), is_best_seller: true, rating: '4.8', review_count: 143 },
  { categorySlug: 'interior', name: 'Car Seat Covers Set', slug: 'car-seat-covers-set', description: 'Universal fit car seat covers. Protects original upholstery.', price: '3500', stock_quantity: 30, condition: 'new', sku: 'INT-SEAT-COVERS', images: getCloudinaryUrls(['IMG_20190204_125858.jpg']), rating: '4.4', review_count: 76 },
  { categorySlug: 'interior', name: 'Car Phone Holder Magnetic', slug: 'car-phone-holder-magnetic', description: 'Strong magnetic phone holder. Dashboard or vent mount.', price: '850', stock_quantity: 80, condition: 'new', sku: 'INT-PHONE-MAG', images: getCloudinaryUrls(['IMG_20190204_133923.jpg']), is_hot_deal: true, rating: '4.7', review_count: 234 },
  { categorySlug: 'interior', name: 'Car Air Freshener Set', slug: 'car-air-freshener-set', description: 'Long-lasting car air fresheners. Multiple scents available.', price: '400', stock_quantity: 100, condition: 'new', sku: 'INT-FRESH-SET', images: getCloudinaryUrls(['IMG_20191020_161653.jpg']), rating: '4.5', review_count: 189 },
  { categorySlug: 'interior', name: 'USB Car Charger Dual Port', slug: 'usb-car-charger-dual', description: 'Fast-charging dual USB car charger. 3.1A total output.', price: '650', stock_quantity: 90, condition: 'new', sku: 'INT-USB-DUAL', images: getCloudinaryUrls(['IMG_20191020_162808.jpg']), is_hot_deal: true, rating: '4.6', review_count: 267 },
  { categorySlug: 'interior', name: 'Bluetooth FM Transmitter', slug: 'bluetooth-fm-transmitter', description: 'Wireless FM transmitter with hands-free calling. USB charging port.', price: '1200', stock_quantity: 55, condition: 'new', sku: 'INT-BT-FM', images: getCloudinaryUrls(['IMG_20191111_141818.png']), rating: '4.5', review_count: 178 },

  // EXTERIOR (20 products)
  { categorySlug: 'exterior', name: 'Allion 260 Headlight Non-Xenon', slug: 'allion-260-headlight-non-xenon', description: 'Halogen headlight for Toyota Allion 260. Left or right available.', price: '9500', stock_quantity: 6, condition: 'used', sku: 'HEAD-ALLION-260', images: getCloudinaryUrls(['Allion_260_headlight_Non_Xenon.jpg']), rating: '4.5', review_count: 12 },
  { categorySlug: 'exterior', name: 'Allion 261 Headlight', slug: 'allion-261-headlight', description: 'Complete headlight assembly for Toyota Allion 261.', price: '10200', stock_quantity: 5, condition: 'used', sku: 'HEAD-ALLION-261', images: getCloudinaryUrls(['Allio_261_headlight.jpg']), rating: '4.6', review_count: 10 },
  { categorySlug: 'exterior', name: 'Allion 265 Headlight', slug: 'allion-265-headlight', description: 'Headlight for Toyota Allion 265. Crystal clear lens.', price: '10800', stock_quantity: 4, condition: 'used', sku: 'HEAD-ALLION-265', images: getCloudinaryUrls(['Allion_265_Headlight.jpg']), rating: '4.7', review_count: 9 },
  { categorySlug: 'exterior', name: 'Toyota Crown 2016 Xenon Headlight', slug: 'toyota-crown-2016-xenon-headlight', description: 'Premium xenon headlight for Toyota Crown 2016. Superior illumination.', price: '32500', compare_at_price: '38000', stock_quantity: 2, condition: 'used', sku: 'HEAD-CROWN-XENON', images: getCloudinaryUrls(['crown_2016_front_headlight_zenon.png']), is_best_seller: true, rating: '5.0', review_count: 5 },
  { categorySlug: 'exterior', name: 'Allion 260 Tail Light', slug: 'allion-260-tail-light', description: 'Tail light assembly for Toyota Allion 260. Left or right side.', price: '7500', stock_quantity: 8, condition: 'used', sku: 'TAIL-ALLION-260', images: getCloudinaryUrls(['Allion_260_tail_light.jpg']), rating: '4.6', review_count: 15 },
  { categorySlug: 'exterior', name: 'Allion 260 Tail Light Lens', slug: 'allion-260-tail-light-lens', description: 'Replacement tail light lens for Allion 260. Perfect fit.', price: '3200', stock_quantity: 12, condition: 'new', sku: 'LENS-ALLION-260', images: getCloudinaryUrls(['Allio_260_taillight_lens.jpg']), rating: '4.5', review_count: 22 },
  { categorySlug: 'exterior', name: 'Allion 265 Tail Light', slug: 'allion-265-tail-light', description: 'Complete tail light for Toyota Allion 265.', price: '7800', stock_quantity: 7, condition: 'used', sku: 'TAIL-ALLION-265', images: getCloudinaryUrls(['Allion_265_Tail_Light.jpg']), rating: '4.6', review_count: 13 },
  { categorySlug: 'exterior', name: 'Allion 265 Tail Light Lens', slug: 'allion-265-tail-light-lens', description: 'Tail light lens cover for Allion 265. Restore clarity.', price: '3400', stock_quantity: 10, condition: 'new', sku: 'LENS-ALLION-265', images: getCloudinaryUrls(['Allion_265_tail_light_lens.jpg']), rating: '4.5', review_count: 19 },
  { categorySlug: 'exterior', name: 'Audi A3 Hatchback Tail Light (2008)', slug: 'audi-a3-hatchback-tail-light-2008', description: 'Tail light for Audi A3 hatchback 2008 model.', price: '12500', stock_quantity: 4, condition: 'used', sku: 'TAIL-A3-HATCH-08', images: getCloudinaryUrls(['AUDI_A3_HATCHBACK_Tail_Light_2008.jpg']), rating: '4.7', review_count: 8 },
  { categorySlug: 'exterior', name: 'Audi A3 Tail Light', slug: 'audi-a3-tail-light', description: 'Standard tail light for Audi A3. High-quality replacement.', price: '11800', stock_quantity: 5, condition: 'used', sku: 'TAIL-A3-STD', images: getCloudinaryUrls(['AUDI_A3_Tail_Light.jpg']), rating: '4.6', review_count: 10 },
  { categorySlug: 'exterior', name: 'Audi A4 B5 Tail Light Right', slug: 'audi-a4-b5-tail-light-right', description: 'Right tail light for Audi A4 B5 generation.', price: '10500', stock_quantity: 3, condition: 'used', sku: 'TAIL-A4-B5-R', images: getCloudinaryUrls(['AUDI_A4_B5_tail_light_right.jpg']), rating: '4.5', review_count: 7 },
  { categorySlug: 'exterior', name: 'Audi A4 Quattro B7 Tail Light', slug: 'audi-a4-quattro-b7-tail-light', description: 'Tail light for Audi A4 Quattro B7. LED type available.', price: '13500', stock_quantity: 4, condition: 'used', sku: 'TAIL-A4-B7-Q', images: getCloudinaryUrls(['AUDI_A4_QUATTRO_B7_Tail_Light.jpg']), rating: '4.8', review_count: 9 },
  { categorySlug: 'exterior', name: 'Audi A6 2008 Tail Light', slug: 'audi-a6-2008-tail-light', description: 'Tail light assembly for Audi A6 2008 model year.', price: '15500', stock_quantity: 3, condition: 'used', sku: 'TAIL-A6-2008', images: getCloudinaryUrls(['Audi_A6_2008_Tail_light.jpg']), rating: '4.9', review_count: 6 },
  { categorySlug: 'exterior', name: 'BMW E91 320i Tail Light', slug: 'bmw-e91-320i-tail-light', description: 'Tail light for BMW 3 Series E91 320i. Premium quality.', price: '16500', stock_quantity: 3, condition: 'used', sku: 'TAIL-BMW-E91', images: getCloudinaryUrls(['BMW_E91_320i_Tail_Light1.jpg']), rating: '4.8', review_count: 8 },
  { categorySlug: 'exterior', name: 'Jaguar X400 Tail Light', slug: 'jaguar-x400-tail-light', description: 'Tail light for Jaguar X400. Rare part, excellent condition.', price: '18500', stock_quantity: 2, condition: 'used', sku: 'TAIL-JAG-X400', images: getCloudinaryUrls(['JAGUAR_X400_Tail_Light.jpg']), rating: '4.9', review_count: 4 },
  { categorySlug: 'exterior', name: 'Honda Vezel 2016 Side Mirror', slug: 'honda-vezel-2016-side-mirror', description: 'Complete side mirror for Honda Vezel 2016. Power and heated.', price: '8500', stock_quantity: 6, condition: 'used', sku: 'MIR-VEZEL-16', images: getCloudinaryUrls(['Honda_Vezel_2016_Side_Mirror_35.jpg']), rating: '4.7', review_count: 14 },
  { categorySlug: 'exterior', name: 'Side Mirror Cover Carbon Fiber', slug: 'side-mirror-cover-carbon', description: 'Carbon fiber side mirror covers. Universal fit, sporty look.', price: '2200', stock_quantity: 40, condition: 'new', sku: 'MIR-COVER-CF', images: getCloudinaryUrls(['IMG_20250517_155337_899.jpg']), is_hot_deal: true, rating: '4.6', review_count: 68 },
  { categorySlug: 'exterior', name: 'Chrome Door Handle Covers', slug: 'chrome-door-handle-covers', description: 'Chrome door handle cover set. Adds premium look.', price: '1800', stock_quantity: 50, condition: 'new', sku: 'EXT-HANDLE-CHROME', images: getCloudinaryUrls(['IMG-20191012-WA0014.jpg']), rating: '4.5', review_count: 92 },
  { categorySlug: 'exterior', name: 'Window Visors Rain Guards', slug: 'window-visors-rain-guards', description: 'Window rain guards set of 4. Allows fresh air even in rain.', price: '2400', stock_quantity: 45, condition: 'new', sku: 'EXT-VISOR-SET', images: getCloudinaryUrls(['IMG-20240917-WA0148.jpg']), is_hot_deal: true, rating: '4.7', review_count: 115 },
  { categorySlug: 'exterior', name: 'Roof Rack Cross Bars', slug: 'roof-rack-cross-bars', description: 'Universal roof rack cross bars. Aluminum construction, 75kg capacity.', price: '6500', stock_quantity: 18, condition: 'new', sku: 'EXT-ROOF-RACK', images: getCloudinaryUrls(['IMG-20240917-WA0153.jpg']), rating: '4.8', review_count: 47 },

  // MAINTENANCE (20 products)
  { categorySlug: 'maintenance', name: 'Engine Oil Filter', slug: 'engine-oil-filter', description: 'Universal engine oil filter. Fits most Japanese vehicles.', price: '450', stock_quantity: 100, condition: 'new', sku: 'FILTER-OIL-UNI', images: getRandomImage(), is_hot_deal: true, rating: '4.6', review_count: 234 },
  { categorySlug: 'maintenance', name: 'Air Filter Element', slug: 'air-filter-element', description: 'High-flow air filter. Improves engine breathing and performance.', price: '800', stock_quantity: 85, condition: 'new', sku: 'FILTER-AIR-UNI', images: getRandomImage(), rating: '4.5', review_count: 187 },
  { categorySlug: 'maintenance', name: 'Cabin Air Filter', slug: 'cabin-air-filter', description: 'HEPA cabin air filter. Removes dust, pollen, and odors.', price: '650', stock_quantity: 75, condition: 'new', sku: 'FILTER-CABIN-UNI', images: getRandomImage(), is_hot_deal: true, rating: '4.7', review_count: 156 },
  { categorySlug: 'maintenance', name: 'Spark Plug Set (4 pieces)', slug: 'spark-plug-set-4pc', description: 'Iridium spark plugs set of 4. Long-lasting performance.', price: '3200', stock_quantity: 45, condition: 'new', sku: 'SPARK-IRID-4PC', images: getRandomImage(), is_best_seller: true, rating: '4.8', review_count: 201 },
  { categorySlug: 'maintenance', name: 'Wiper Blade Set', slug: 'wiper-blade-set', description: 'Premium wiper blade set. All-weather performance.', price: '1200', stock_quantity: 60, condition: 'new', sku: 'WIPER-SET-UNI', images: getRandomImage(), rating: '4.6', review_count: 143 },
  { categorySlug: 'maintenance', name: 'Engine Oil 5W-30 (4L)', slug: 'engine-oil-5w30-4l', description: 'Fully synthetic engine oil 5W-30. API SN/CF certified.', price: '2800', stock_quantity: 40, condition: 'new', sku: 'OIL-5W30-4L', images: getRandomImage(), is_best_seller: true, rating: '4.9', review_count: 312 },
  { categorySlug: 'maintenance', name: 'Engine Oil 10W-40 (4L)', slug: 'engine-oil-10w40-4l', description: 'Semi-synthetic engine oil 10W-40. Suitable for high mileage vehicles.', price: '2200', stock_quantity: 50, condition: 'new', sku: 'OIL-10W40-4L', images: getRandomImage(), rating: '4.7', review_count: 278 },
  { categorySlug: 'maintenance', name: 'Coolant/Antifreeze (5L)', slug: 'coolant-antifreeze-5l', description: 'Premium engine coolant. Protects from -40°C to +130°C.', price: '1800', stock_quantity: 55, condition: 'new', sku: 'COOL-5L-UNI', images: getRandomImage(), is_hot_deal: true, rating: '4.6', review_count: 189 },
  { categorySlug: 'maintenance', name: 'Windshield Washer Fluid (5L)', slug: 'windshield-washer-fluid-5l', description: 'All-season washer fluid. Removes bugs and road grime.', price: '600', stock_quantity: 80, condition: 'new', sku: 'WASH-5L-UNI', images: getRandomImage(), rating: '4.5', review_count: 167 },
  { categorySlug: 'maintenance', name: 'Fuel System Cleaner', slug: 'fuel-system-cleaner', description: 'Fuel injector cleaner. Restores power and improves fuel economy.', price: '950', stock_quantity: 70, condition: 'new', sku: 'CLEAN-FUEL-UNI', images: getRandomImage(), rating: '4.7', review_count: 224 },
  { categorySlug: 'maintenance', name: 'Engine Degreaser Spray', slug: 'engine-degreaser-spray', description: 'Powerful engine degreaser. Makes cleaning easy.', price: '750', stock_quantity: 65, condition: 'new', sku: 'CLEAN-ENG-SPRAY', images: getRandomImage(), is_hot_deal: true, rating: '4.6', review_count: 142 },
  { categorySlug: 'maintenance', name: 'Tire Shine Gel', slug: 'tire-shine-gel', description: 'Long-lasting tire shine. UV protection included.', price: '550', stock_quantity: 90, condition: 'new', sku: 'SHINE-TIRE-GEL', images: getRandomImage(), rating: '4.5', review_count: 198 },
  { categorySlug: 'maintenance', name: 'Car Wash Shampoo (1L)', slug: 'car-wash-shampoo-1l', description: 'pH-balanced car wash shampoo. Safe for all finishes.', price: '650', stock_quantity: 75, condition: 'new', sku: 'WASH-SHAM-1L', images: getRandomImage(), rating: '4.6', review_count: 176 },
  { categorySlug: 'maintenance', name: 'Microfiber Towel Set', slug: 'microfiber-towel-set', description: 'Premium microfiber towels set of 3. Scratch-free cleaning.', price: '850', stock_quantity: 85, condition: 'new', sku: 'TOWEL-MF-3PC', images: getRandomImage(), rating: '4.7', review_count: 203 },
  { categorySlug: 'maintenance', name: 'Wheel Cleaner Spray', slug: 'wheel-cleaner-spray', description: 'Acid-free wheel cleaner. Removes brake dust easily.', price: '800', stock_quantity: 60, condition: 'new', sku: 'CLEAN-WHEEL-SPR', images: getRandomImage(), is_hot_deal: true, rating: '4.8', review_count: 167 },
  { categorySlug: 'maintenance', name: 'Polish & Wax Combo', slug: 'polish-wax-combo', description: 'Car polish and carnauba wax set. Professional results.', price: '1500', stock_quantity: 50, condition: 'new', sku: 'WAX-COMBO-SET', images: getRandomImage(), rating: '4.9', review_count: 289 },
  { categorySlug: 'maintenance', name: 'Touch-Up Paint Pen', slug: 'touch-up-paint-pen', description: 'Universal touch-up paint pen. Multiple colors available.', price: '450', stock_quantity: 95, condition: 'new', sku: 'PAINT-PEN-UNI', images: getRandomImage(), rating: '4.4', review_count: 134 },
  { categorySlug: 'maintenance', name: 'Rubber Seal Conditioner', slug: 'rubber-seal-conditioner', description: 'Protects and restores rubber seals and trim.', price: '650', stock_quantity: 70, condition: 'new', sku: 'COND-SEAL-RUB', images: getRandomImage(), rating: '4.6', review_count: 98 },
  { categorySlug: 'maintenance', name: 'Battery Terminal Cleaner', slug: 'battery-terminal-cleaner', description: 'Cleans and protects battery terminals from corrosion.', price: '550', stock_quantity: 80, condition: 'new', sku: 'CLEAN-BATT-TERM', images: getRandomImage(), is_hot_deal: true, rating: '4.7', review_count: 187 },
  { categorySlug: 'maintenance', name: 'Multi-Purpose Lubricant Spray', slug: 'multi-purpose-lubricant', description: 'WD-40 style lubricant. Stops squeaks and loosens rust.', price: '750', stock_quantity: 90, condition: 'new', sku: 'LUB-MULTI-SPRAY', images: getRandomImage(), rating: '4.8', review_count: 245 },
];
